### ISSUE TITLE
Get reference genome from Genstat

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC_NGI#20]
I just talked to Mattias about the Genomic status MultiQC implementation and Fastqc screen in particular. He suggested that it would be useful if MultiQC could fetch what reference genome the project has from genstat and display that in the fastqscreen report. I don't really have a good grasp on whether this is feasible or not.

**Comment by ewels** [comment]
How do you mean? As in just print it in the report as text somewhere? Should be v. easy if so. Can see how it's done for the text at the top of the report and just repeat it for the extra field.

**Comment by ewels** [comment]
ps. "Text at the top of the report" = info about what sequencing technology was used and email address etc.

**Comment by ewels** [comment]
@Hammarn - let me know if you want me to write this. If you want to have a crack we can chat about it and I can suggest how to go about writing it.

**Comment by ewels** [comment]
#21 needs to be done before this is started.

**Comment by ewels** [comment]
Closed in #23
