### ISSUE TITLE
Heatmap breaks with many samples

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC_NGI#27]
Thea heatmap tends to break when the number of samples get "too big". After talking to Jun we think that the range in which the plot breaks is somewhere between 20-32 samples. Which is a fairly common amount of samples in a project. 

Example of how the broken plot looks like here:
![mqc_hcplot_gjawkirzfh](https://cloud.githubusercontent.com/assets/16774076/25432941/d8054084-2a86-11e7-9dcf-4374a3cfb7b1.png)

A broken report can be found here:
https://genomics-status.scilifelab.se/multiqc_report/P7364

**Comment by ewels** [comment]
Ok cool - if we could dig out some source files that trigger this too, that would be great (should be pretty easy by the sound of it). Can DM those to me.

Phil

**Comment by ewels** [comment]
This is a core MultiQC bug. Moving to the main MultiQC repository.
